config/routes.rb
Details::Application.routes.draw do

  devise_for :users  do
    get 'logout' => 'devise/sessions#destroy'

  end

  resources :employee do
 post "search", :on=>:collection
 end

   root :to => 'employee#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
   attr_accessible  :email_id ,:created_at,:password, :department ,:forwards , :category,:group_head,
                       :requisition_by, :handled_by, :employee_id, :delete_on, :uuid , :status



  #validates  :department ,:forwards , :category,:group_head,
            #:requisition_by, :handled_by,       :presence=> true

   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email_id, presence: true, format: { with: VALID_EMAIL_REGEX }

  def self.dept
    dept1=Employee.select(:department).uniq
    dept_aray=[]
    dept1.each do |d|
      dept_aray.push(d[:department])
    end
    return dept_aray
  end

  def self.catg
    catg1=Employee.select(:category).uniq
    cat_array=[]
    catg1.each do |c|
      cat_array.push(c[:category])
    end
    return cat_array
  end


  def self.mang
    mang1=Employee.find_by_sql("select distinct forwards from employees
                        union select distinct group_head from employees
                        union  select distinct handled_by from employees
                        union select distinct requisition_by from employees;")
    mang_array=[]
    mang1.each do |m|
      mang_array.push(m[:forwards])
    end
    return mang_array
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me ,:name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
 before_filter :authenticate_user!

  def index

    @emps= Employee.paginate(:page => params[:page], :per_page=>5).find(:all, :conditions => ["status='0' OR status='1' ", status])
   #@emps=Employee.all
  end

  def new
    @emp= Employee.new

  end


  def create

      @emp=Employee.new(params[:employee])
         u=UUID.new
       @emp.uuid=u.generate[1,7]
    if @emp.save
       redirect_to  employee_index_path
      flash[:error] ="new data created"
    else
      flash.now[:error] = "Can't  save data"
      render :action => "new"
    end

  end
  
  def search
    @emp=Employee.find(:all, :conditions=>['email_id LIKE?  OR status LIKE? OR forwards LIKE?  OR group_head LIKE? OR department LIKE? OR category  LIKE?
                                                OR requisition_by LIKE? OR forwards LIKE? ',
                                        "#{params[:department]}","#{params[:department]}","#{params[:department]}",
                                        "#{params[:department]}","#{params[:department]}","#{params[:department]}","#{params[:department]}","#{params[:department]}"])

     #@emp=Employee.find(:all,:conditions=>['id =?', "#{params[:id]}"])          #use if we wants to search on basis or id because id is integer left are string or charter.

  end



  def show
   @emp=Employee.find(params[:id])
  end

  def edit
    @emp=Employee.find(params[:id])
  end

  def update
    @emp=Employee.find(params[:id])
    if @emp.update_attributes(params[:employee])
      redirect_to :action=>'index'
      flash[:error] ="Values updated "
    else
      render 'edit'
      flash[:error]= "update properly"
    end
  end

  def destroy
    @emp=Employee.find(params[:id])
    @emp.update_attribute(:status,'2')
    redirect_to :action=>'index'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employee/edit.html.haml
%h1 Edit
%center
  = form_for @emp do |emp|
    %b Email_id
    = emp.text_field :email_id
    %br/
    %b Create_at
    = emp.date_select :created_at
    %br/
    %br/
    %b department
    = emp.text_field :department, :id => "autocomplete1"

    %br
    %b Forwarded_to
    = emp.text_field :forwards, :id =>"autocomplete2"
    %br/
    %b Category
    = emp.text_field :category, :id =>"autocomplete3"
    %br/
    %b Group_Head
    = emp.text_field :group_head, :id =>"autocomplete4"
    %br/
    %b Requisition_By
    = emp.text_field :requisition_by, :id =>"autocomplete5"
    %br/
    %b Handled_By
    = emp.text_field :handled_by, :id =>"autocomplete6"
    %br/
    = emp.hidden_field :status, :value=>'1'
    = emp.submit






        
        
        
        

app/views/employee/index.html.haml
%h1 Lists
%p.error= flash[:error]
= will_paginate  @emps
%div{:align => "right"}
  = form_tag :controller=>'employee', :action=>'search', :method=> :get do |src|
    = text_field_tag 'department'
    = submit_tag "search"
%br/
%br/
%table{:align => "center", :border => "1"}
  %tr
    %th Serial_no
    %th Email_id
    %th Created_on
    %th Department
    %th Forward
    %th Category
    %th Group_Head
    %th Requisition_By
    %th Handled_by
    %th show
    %th update
    %th delete

  - @emps.each do |emp,i|

    %tr
      %td= emp.id
      %td= link_to emp.email_id, emp
      %td= emp.created_at
      %td= emp.department
      %td= emp.forwards
      %td= emp.category
      %td= emp.group_head
      %td= emp.requisition_by
      %td= emp.handled_by
      %td= link_to image_tag("arrow-left.png",:width=>20),emp
      %td
        = link_to image_tag("update.png",:width=>20),edit_employee_path(emp)
        %td
          = link_to image_tag("Delete-icon.png",:width=>20),emp,:confirm=>'Are you sure?', method:  :delete
        //i=i+1
%b= link_to 'Enter new details', new_employee_path

app/views/employee/new.html.haml
- if @emp.errors.any?
  #errorExplanation
    %h2
      = pluralize(@emp.errors.count, "error")
      prohibited this asset from being saved:
    %ul
      - @emp.errors.full_messages.each do |msg|
        %li= msg

%h1 Please Fill the details
%h1
  %p.error= flash[:error]
= form_for @emp, :url=>{:action=>'create'} do |emp|
  %b Email_id
  =emp.text_field :email_id
  %br/
  %br/

  %b Create_at
  = emp.date_select :created_at
  %br/
  %br/

  %b department
  = emp.text_field :department, :id =>"autocomplete1"

  =# emp.select(:department,["HRA","ADMIN","TESTER","DEVELOPER"] , :prompt => ' ',:class => 'space_bottom quote_request_form')
  %br/
  %br/
  %b Forwarded_to
  =emp.text_field :forwards, :id=>"autocomplete2"
  -#%input#autocomplete2/
  =# emp.select(:forwards,["srinivas","ramappa","samar","vineeth"] , :prompt => 'Select',:class => 'space_bottom quote_request_form')
  %br/
  %br/
  %b Category
  =emp.text_field :category, :id=>"autocomplete3"
  =#%input#autocomplete3/
  =# emp.select(:category, ["Relyonist","Client","Customer"],:prompt =>'select', :class=>'space_button quote_request_form' )
  %br/
  %br/
  %b Group_Head
  =emp.text_field :group_head, :id=>"autocomplete4"
  =#%input#autocomplete4/
  =# emp.select(:group_head,["srinivas","ramappa","samar","vineeth"] , :prompt => 'Select',:class => 'space_bottom quote_request_form')
  %br/
  %br
  %b Requisition_By
  =emp.text_field :requisition_by, :id=>"autocomplete5"
  =#%input#autocomplete5/
  =# emp.select(:requisition_by,["srinivas","ramappa","samar","vineeth"] , :prompt => 'Select',:class => 'space_bottom quote_request_form')
  %br/
  %br/
  %b Handled_By
  =emp.text_field :handled_by, :id=>"autocomplete6"
  =#%input#autocomplete6/
  =# emp.select(:handled_by,["srinivas","ramappa","samar","vineeth"] , :prompt => 'Select',:class => 'space_bottom quote_request_form')
  %br/
  %br/
  = emp.hidden_field :status, :value=> '0'
  = emp.submit'Create'

app/views/employee/search.html.haml
%h1 Search result
- if (@emp.length==0)
  %p
    %h3 There is no related data please enter correct data
- else
  %table{:align=>"center",:border=>"1"}
    %tr
      %th Serial_no
      %th Email_id
      %th Created_on
      %th Department
      %th Forward
      %th Category
      %th Group_Head
      %th Requisition_By
      %th Handled_by
      %th Employee_id
      %th status
      %th
      %th
      %th
    - @emp.each do |emp|
      %tr
        %td= emp.id
        %td=link_to emp.email_id, emp
        %td= emp.created_at
        %td= emp.department
        %td= emp.forwards
        %td= emp.category
        %td= emp.group_head
        %td= emp.requisition_by
        %td= emp.handled_by
        %td= emp.id
        %td= emp.status
        %td= link_to 'show',emp
        %td= link_to 'edit',edit_employee_path(emp)
        %td= link_to 'destroy ', emp,:confirm=>'Are you sure?', method:  :delete
= link_to 'back', employee_index_path

app/views/employee/show.html.haml
%h1 Details
%center
  %p
    %b Serial_no:
    = @emp.id

  %p
    %b Create_at:
    = @emp.created_at
  %p
    %b Email_id:
    = @emp.email_id
  %p
    %b password:
    = @emp.uuid
  %p
    %b Handled_by:
    = @emp.handled_by
  %p
    %b Emp_id:
    = @emp.id
  %p
    %b Department:
    = @emp.department
  %p
    %b Forwards:
    = @emp.forwards
  %p
    %b Group_head:
    = @emp.group_head
  %p
    %b Requisition_By:
    = @emp.requisition_by
  %p
    %b Status:
    = @emp.status
= link_to 'index', employee_index_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
      <title>Details</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= stylesheet_link_tag    "global", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
  <script>
      $(document).ready(function() {
          var department = [];
          <%
            department = Employee.dept
            department.each do |dept|
           %>
            department.push("<%=     dept%>");

          <%
            end
          %>

          var category = [];
          <%
            category=Employee.catg
            category.each do |cat|
          %>

             category.push("<%= cat %>");
           <%
             end
           %>

           var manager = [];
          <% manager=Employee.mang
             manager.each do |mang|
          %>
              manager.push("<%= mang %>");
          <%
            end
          %>


        $("input#autocomplete1").autocomplete({
            source: department
        });
          $("input#autocomplete2").autocomplete({
              source: manager
          });
          $("input#autocomplete3").autocomplete({
              source: category
          });
          $("input#autocomplete4").autocomplete({
              source: manager
          });
          $("input#autocomplete5").autocomplete({
              source: manager
          });$("input#autocomplete6").autocomplete({
              source: manager
          });
      });
  </script>

</head>



 <body>
 <div id="container" style="width:1350px ">

   <div id="header" style="background-color:#FFA500;">
     <h2 align= "center">Welcome in Employee details form</h2>
   </div>
    <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out", logout_path %>

        <%= link_to "Edit account",edit_user_registration_path%>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
    <% end %>
    </div>
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

   <br/><br/><br/><br/><br/><br/>


<div align="right">
        <a href="http://guides.rubyonrails.org/">
         <img src="/assets/R.png" width="75" height="75"></a>
      <a href="http://www.gmail.com">
         <img src="/assets/g+.jpeg" width="75" height="75"></a>
      <a href="http://ruby.railstutorial.org/">
        <img src="assets/R1.png" width="75" height="75">
      </a> 
</div>




          <div id="footer" style="background-color:#FFA500;clear:both;text-align:center;height:50px "> <br/>
            Copyright © prashantmishra.com</div>

</body>
</html>